# Generated by Django 2.2.3 on 2019-07-11 04:28

import apps.textrecognizer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImageModel',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('image', models.ImageField(storage=apps.textrecognizer.models.OverwriteStorage(), upload_to='uploadedImages')),
            ],
        ),
    ]
