# Generated by Django 2.2.3 on 2019-07-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImageModel',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('uploadedImage', models.ImageField(upload_to='uploadedImages')),
            ],
        ),
    ]
